### ISSUE TITLE
Doesn't update the URI when reconnecting with new keys

### ISSUE THREAD

**Issue by stooone** [syncthing/relaypoolsrv#3]
Hi,

I restarted my relaysrv (in a docker container) so regenerated the keys, the URI, id, etc... then rejoined the relaypoolsrv in several seconds/minutes later. But he relaypoolsrv haven't updated my URI so my id remained the old one. And it seems that now noone is able to successfully connect me.

Cheers,

Stone

**Comment by AudriusButkevicius** [comment]
Yeah, the old entry will timeout in 30 minutes and it will use the new URL.

**Comment by stooone** [comment]
Oh I see... wouldn't it be a good idea to overwrite the old entry when the same IP rejoins?

**Comment by AudriusButkevicius** [comment]
I'm fixing it now.

**Comment by stooone** [comment]
Thanks!:)
